#!/bin/sh
cd ${0%/*} || exit 1    # Run from this directory

# Compile OpenFOAM libraries and applications

wmake all thermophysicalModels 

#------------------------------------------------------------------------------
