#!/bin/sh
cd ${0%/*} || exit 1    # Run from this directory

thirdParty/Allwmake

# Compile OpenFOAM libraries and applications
src/Allwmake $targetType $*

applications/Allwmake $targetType $*


#------------------------------------------------------------------------------
