#!/bin/sh

if ! which gnuplot > /dev/null 2>&1
then
    echo "gnuplot not found - skipping graph creation" >&2
    exit 1
fi

rm -f *.pdf *.eps

time=$(foamListTimes -case ../ -latestTime)

graphFile=../postProcessing/sample/$time/data.xy
expData=exp.xy
kurganov=kurganov.xy

plotGraph() {

gnuplot <<EOF
    set terminal pdfcairo enhanced color font "Helvetica,16"
    set output '$1.pdf'

    set xlabel 'l (m)'
    set ylabel '$1 ($2)'
    set ytics nomirror
    set key top left

    # Compute minimum y-value from both files (column 4)
    stats "$graphFile" using $3 nooutput
    ymin1 = STATS_min
    stats "$kurganov" using $3 nooutput
    ymin2 = STATS_min

    ymin = (ymin1 < ymin2) ? ymin1 : ymin2
    ylower = ymin * 0.9
    set yrange [ylower:*]

    # Define custom line styles
    set style line 1 dashtype (5,3) lw 3 lc rgb "black"  # Thicker dashed black for AUSM+
    set style line 2 lw 2 lc rgb "gray"                  # Solid grey for KP

      # For transparent (empty) black circles
    set style line 3 pt 6 ps 0.35 lc rgb "black" lw 1

    plot \
         "$expData"   u 1:$3 w p ls 3 t 'exp', \
         "$graphFile" u 1:$3 w l ls 1 t 'AUSM+', \
         "$kurganov"  u 1:$3 w l ls 2 t 'KP'
EOF
}


# T
plotGraph T K 2;

# U
plotGraph U "m/s" 3;

# p
plotGraph p Pa 4;

#------------------------------------------------------------------------------
